// CVS ID: @(#) $Id: Properties.java,v 1.1.1.1 2005-08-25 18:13:09 husker Exp $

package com.talient.util;

import java.io.PrintWriter;
import java.io.PrintStream;
import java.io.FileInputStream;
import java.io.IOException;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;


/**
 * This class provides standard access to properties files for the
 * com.talient.* packages.  The utility methods in this class will
 * look in up to two possible locations for properties.  If the
 * property being requested is set in the system properties, the
 * methods will return that value.
 *
 * If the value is not set in the system properties, the methods in
 * this class will look to see if the "util.property.filename" property
 * is set in the system proerties.  If so, the class will open up
 * the specified file and use it as the secondary source for property
 * settings.
 *
 * If "util.property.filename" property is not set, the class will
 * use ".talient.properties" under the user's home directory (as
 * defined by the system "user.home" property, of course) as the
 * secondary source of property settings.
 *
 * If that file does not exist or is corrupt (or if the file pointed
 * to by the "util.property.filename" does not exist or is corrupt),
 * the class will still prepare a set of properties initialized with
 * two values.  The first value, "util.property.filename", will
 * contain the name of the file that the class attempted to open.
 * The second value, "util.property.exception", will contain the
 * exception that was generated by the attempt.
 *
 * The "util.property.filename" property will always be set, even on
 * a successful load.
 *
 * Like the getProperty methods, the list methods in this class first
 * dump the values from the system properties and then the values from
 * the secondary property file.
 */
public final class Properties {

    private Properties() {}

    private static java.util.Properties properties = null;
    private static String filename = null;
    private static InitialContext initCtx = null;
    private static Context defCtx = null;

    public static String getProperty(String key) {
        String value = getEnvEntry(key);
        if (value == null) {
            final String systemProperty =
                System.getProperties().getProperty(key);
            if (systemProperty != null) {
                return systemProperty;
            } else {
                return getProperties().getProperty(key);
            }
        }
        return value;
    }

    public static String getProperty(String key, String defaultValue) {
        String value = getEnvEntry(key);
        if (value == null) {
            final String systemProperty =
                System.getProperties().getProperty(key);
            if (systemProperty != null) {
                return systemProperty;
            } else {
                return getProperties().getProperty(key, defaultValue);
            }
        }
        return value;

    }

    public static void setFilename(String fn) {
        filename = fn;
    }

    public static String getFilename() {
        return filename;
    }

    public static void list(PrintStream out) {
        System.getProperties().list(out);
        getProperties().list(out);
    }

    public static void list(PrintWriter out) {
        System.getProperties().list(out);
        getProperties().list(out);
    }

    private static java.util.Properties getProperties() {
        if (properties == null) {

            if (filename == null) {
                filename =
                    System.getProperties().getProperty(
                        "util.property.filename",
                        System.getProperties().getProperty("user.home") +
                        System.getProperties().getProperty("file.separator") +
                        ".talient.properties");
            }

            try {
                properties = new java.util.Properties();
                properties.load(new FileInputStream(filename));
                properties.setProperty("util.property.filename", filename);
            } catch (IOException e) {
                properties.setProperty("util.property.filename", filename);
                properties.setProperty("util.property.exception", e.toString());
            }
        }
        return properties;
    }

    private static String getEnvEntry(String key) {
        try {
            if (defCtx == null) {
                initCtx = new InitialContext();
                defCtx = (Context)initCtx.lookup("java:comp/env");
            }
            return (String)defCtx.lookup(key);
        }
        catch (NamingException ne) {
            return null;
        }
        catch (Exception e) {
            return null;
        }
    }

    public static void main(String argv[]) {
        list(System.out);

        System.out.println("\n\ngetProperty(\"java.version\") = \"" +
            getProperty("java.version") + "\"\n");

        System.out.println("getProperty(\"java.version\", \"default\") = \"" +
            getProperty("java.version", "default") + "\"\n");

        System.out.println("getProperty(\"football.database.url\") = \"" +
            getProperty("football.database.url") + "\"\n");

        System.out.println(
            "getProperty(\"football.database.url\", \"default\") = \"" +
            getProperty("football.database.url", "default") + "\"\n");

        System.out.println("getProperty(\"nonsense.property\") = \"" +
            getProperty("nonsense.property") + "\"\n");

        System.out.println(
            "getProperty(\"nonsense.property\", \"default\") = \"" +
            getProperty("nonsense.property", "default") + "\"\n");
    }
}
